flowinquiry/flowinquiry

- server/src/main/java/io/flexwork/modules/usermanagement/service/UserService.java
- server/src/main/java/io/flexwork/modules/usermanagement/web/rest/AuthorityController.java
> Delete user from authority api

- server/src/main/java/io/flexwork/modules/crm/service/dto/AccountDTO.java
- server/src/main/java/io/flexwork/modules/crm/service/mapper/AccountMapper.java
> Support parent account fields

- server/src/main/java/io/flexwork/modules/usermanagement/domain/Team.java
- server/src/main/java/io/flexwork/modules/usermanagement/repository/AuthorityRepository.java
- server/src/main/java/io/flexwork/modules/usermanagement/repository/TeamRepository.java
- server/src/main/java/io/flexwork/modules/usermanagement/repository/UserRepository.java
- server/src/main/java/io/flexwork/modules/usermanagement/service/AuthorityService.java
- server/src/main/java/io/flexwork/modules/usermanagement/service/TeamService.java
- server/src/main/java/io/flexwork/modules/usermanagement/service/UserService.java
- server/src/main/java/io/flexwork/modules/usermanagement/service/dto/UserDTO.java
- server/src/main/java/io/flexwork/modules/usermanagement/web/rest/AuthorityController.java
- server/src/main/java/io/flexwork/modules/usermanagement/web/rest/PublicUserController.java
- server/src/main/java/io/flexwork/modules/usermanagement/web/rest/TeamController.java
> Add user team apis

- gradle/libs.versions.toml
- server/build.gradle
- server/src/main/java/io/flexwork/modules/collab/domain/Notification.java
- server/src/main/java/io/flexwork/modules/collab/repository/NotificationRepository.java
- server/src/main/java/io/flexwork/modules/collab/service/NotificationService.java
- server/src/main/java/io/flexwork/modules/collab/service/dto/NotificationDTO.java
- server/src/main/java/io/flexwork/modules/collab/service/dto/OrganizationDTO.java
- server/src/main/java/io/flexwork/modules/collab/service/event/NewTeamRequestCreatedEvent.java
- server/src/main/java/io/flexwork/modules/collab/service/listener/TeamRequestEventListener.java
- server/src/main/java/io/flexwork/modules/collab/service/mapper/NotificationMapper.java
- server/src/main/java/io/flexwork/modules/collab/web/rest/NotificationController.java
- server/src/main/java/io/flexwork/modules/teams/service/TeamRequestService.java
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/00000000000000_initial_schema.xml
> Notification back end

- server/src/main/resources/config/application-prod.yml
- server/src/main/resources/config/application.yml
- server/src/main/resources/i18n/messages.properties
- server/src/test/resources/config/application.yml
- tools/liquibase/src/main/resources/config/liquibase/master/changelog/001_initial_schema.xml
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/000_initial_schema.xml
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/001_request_workflow_tables.xml
> Change brand name

- server/src/main/java/io/flowinquiry/modules/teams/service/mapper/TeamRequestMapper.java
- server/src/main/java/io/flowinquiry/modules/usermanagement/service/mapper/UserMapper.java
- server/src/main/resources/config/application-dev.yml
- server/src/test/java/io/flowinquiry/web/rest/UserControllerIT.java
> User mapper correction

- README.md
- server/src/main/java/io/flowinquiry/modules/usermanagement/repository/UserRepository.java
- server/src/main/java/io/flowinquiry/modules/usermanagement/service/UserService.java
- server/src/main/java/io/flowinquiry/modules/usermanagement/service/dto/UserHierarchyDTO.java
- server/src/main/java/io/flowinquiry/modules/usermanagement/web/rest/PublicUserController.java
- server/src/test/java/io/flowinquiry/web/rest/UserControllerIT.java
> Orgchart api

- build.gradle
- commons/src/main/java/io/flowinquiry/modules/teams/service/listener/RemoveUserOutOfTeamEventListener.java
- commons/src/main/resources/i18n/messages_en.properties
- commons/src/main/resources/templates/mail/activationEmail.html
- commons/src/main/resources/templates/mail/creationEmail.html
- commons/src/main/resources/templates/mail/footer.html
- commons/src/main/resources/templates/mail/header.html
- commons/src/main/resources/templates/mail/passwordResetEmail.html
> Mail templates

- .github/workflows/gradle.yml
- README.md
- build.gradle
- gradle.properties
> Deploy common libs to GitHub packages

- commons/src/main/java/io/flowinquiry/config/SecurityConfiguration.java
- commons/src/main/java/io/flowinquiry/modules/fss/ResourceRemoveEvent.java
- commons/src/main/java/io/flowinquiry/modules/fss/controller/FileDownloadController.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/controller/PublicUserController.java
> Protected resources

- commons/build.gradle
- commons/src/main/java/io/flowinquiry/config/AppAuthenticationManagerConfiguration.java
- commons/src/main/java/io/flowinquiry/config/SecurityConfiguration.java
- commons/src/main/java/io/flowinquiry/config/SecurityJwtConfiguration.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/controller/AuthenticateController.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/controller/LoginController.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/service/DomainUserDetailsService.java
- server/src/main/resources/config/application-dev.yml
> Refactor security workflow

- .env.local.example
- README.md
> Add the sample config file

- commons/src/main/java/io/flowinquiry/modules/ai/service/ChatModelService.java
- commons/src/main/java/io/flowinquiry/modules/ai/service/OllamaChatModelService.java
- commons/src/main/java/io/flowinquiry/modules/ai/service/OpenAiChatModelService.java
- commons/src/main/java/io/flowinquiry/modules/teams/controller/WorkflowController.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/Workflow.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/TeamWorkflowSelectionRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/WorkflowRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/WorkflowTransitionRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamRequestHealthEvalService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/WorkflowService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/WorkflowDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/WorkflowMapper.java
- commons/src/main/resources/templates/mail/newTicketEmail.html
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/001_request_workflow_tables.xml
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_workflow_dev.csv
> Workflow management

- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamService.java
- server/src/test/java/io/flowinquiry/modules/teams/service/TeamServiceIT.java
* Add the integration test for the Team Service
* Minor improvement the Team Service implementation
> Add integration test for the Team Service

- commons/src/main/java/io/flowinquiry/config/SchedulerConfiguration.java
- commons/src/main/java/io/flowinquiry/modules/shared/domain/DeduplicationCacheEntry.java
- commons/src/main/java/io/flowinquiry/modules/shared/reppository/DeduplicationCacheRepository.java
- commons/src/main/java/io/flowinquiry/modules/shared/service/cache/CaffeineDeduplicationCache.java
- commons/src/main/java/io/flowinquiry/modules/shared/service/cache/DeduplicationCacheService.java
- commons/src/main/java/io/flowinquiry/modules/shared/service/job/DeduplicationCacheCleanupJob.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/WorkflowTransitionHistoryStatus.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/TeamRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/WorkflowTransitionHistoryRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/WorkflowTransitionHistoryService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/job/SendNotificationForTicketsViolateSlaJob.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/job/SendWarningForUpcomingTicketsViolateSlaJob.java
- commons/src/main/java/io/flowinquiry/modules/teams/utils/DeduplicationKeyBuilder.java
- commons/src/main/resources/i18n/messages_en.properties
- commons/src/main/resources/templates/mail/violatedSlaTicketEmail.html
- server/src/main/java/io/flowinquiry/FlowInquiryApp.java
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/000_initial_schema.xml
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/001_request_workflow_tables.xml
> Workflow sla notifications

- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamRequestService.java
- commons/src/main/java/io/flowinquiry/query/QueryUtils.java
> Fix the type compatible issue

- commons/src/main/java/io/flowinquiry/modules/collab/controller/EntityWatcherController.java
- commons/src/main/java/io/flowinquiry/modules/collab/domain/EntityWatcher.java
- commons/src/main/java/io/flowinquiry/modules/collab/repository/EntityWatcherRepository.java
- commons/src/main/java/io/flowinquiry/modules/collab/service/EntityWatcherService.java
- commons/src/main/java/io/flowinquiry/modules/collab/service/mapper/EntityWatcherMapper.java
- commons/src/main/java/io/flowinquiry/modules/fss/service/dto/EntityWatcherDTO.java
- commons/src/main/java/io/flowinquiry/modules/fss/service/mapper/EntityWatcherMapper.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/TeamRequest.java
> Add more attributes to watcher

- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamRequestService.java
There is a bug in the TeamRequestService when user create a new team request, they are not automatically added to the watcher list
Update the TeamRequestService to automatically add the requester and assigned user to the watcher list of the newly created request.
> When a user creates a new team request, they are not automatically added to the watcher list

- commons/build.gradle
- gradle.properties
- gradle/libs.versions.toml
> Release v1.0

- README.md
- commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectController.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectService.java
- commons/src/main/java/io/flowinquiry/query/QueryUtils.java
> Project management queries

- README.md
> Update contributors section

- commons/src/main/java/io/flowinquiry/modules/teams/domain/Project.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/event/NewProjectCreatedEvent.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/listener/NewProjectCreatedNotificationEventListener.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/ProjectMapper.java
- server/src/test/java/io/flowinquiry/modules/teams/service/ProjectServiceIT.java
* Add the notification for creating new project
* Fix the issue the project do not have the create user id
* Update integration test
> Add the notification for creating new project and minor other updates

- commons/src/main/java/io/flowinquiry/modules/teams/controller/TeamController.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/controller/PublicUserController.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/repository/UserRepository.java
- commons/src/main/java/io/flowinquiry/modules/usermanagement/service/UserService.java
- commons/src/main/java/io/flowinquiry/query/QueryUtils.java
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_workflow_transition_dev.csv
> Project user aips

- commons/src/main/java/io/flowinquiry/query/QueryUtils.java
> Fix query utils

- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamRequestService.java
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_workflow_state_dev.csv
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_workflow_state_prod.csv
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_workflow_transition_dev.csv
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_workflow_transition_prod.csv
> Fix predefined date

- commons/src/main/java/io/flowinquiry/modules/teams/controller/TeamRequestController.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/TeamRequestRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/TeamRequestService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/TeamRequestDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/TeamRequestMapper.java
- server/src/test/java/io/flowinquiry/modules/teams/service/TeamRequestServiceIT.java
> Project navigation api

- commons/src/main/java/io/flowinquiry/modules/teams/repository/TeamRequestRepository.java
In my local installation, I discovered that the query counting overdue tickets per time range is incorrect. The query retrieves data by joining requests with workflow transition history but only considers the latest entry
> Correct the query to accurately count overdue tickets

- commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectEpicController.java
- commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectIterationController.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/ProjectEpic.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/ProjectIteration.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/TeamRequest.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectEpicRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectIterationRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectEpicService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectIterationService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectEpicDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectIterationDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/TeamRequestDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/ProjectEpicMapper.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/ProjectIterationMapper.java
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/001_request_workflow_tables.xml
> Project iteration and epic

- commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectController.java
- commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectEpicController.java
- commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectIterationController.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/ProjectEpic.java
- commons/src/main/java/io/flowinquiry/modules/teams/domain/ProjectIteration.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectIterationRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/repository/TeamRequestRepository.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectEpicService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectIterationService.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectEpicDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectIterationDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/dto/TeamRequestDTO.java
- commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/TeamRequestMapper.java
- commons/src/main/java/io/flowinquiry/utils/BaseMapper.java
- server/src/main/resources/config/application.yml
> Project iteration and epics api

- server/src/test/java/io/flowinquiry/modules/teams/service/TeamRequestServiceIT.java
- server/src/test/java/io/flowinquiry/modules/teams/service/TeamServiceIT.java
- tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/001_request_workflow_tables.xml
- tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_team_request_test.csv
> Team requst integration test update

- README.md
- apps/docs/src/app/developer_guides/page.mdx
- tools/setup/backend-env.sh
> Make scripts run on windows

- apps/docs/src/app/developer_guides/backend/getting_started/page.mdx
- apps/docs/src/app/developer_guides/deployment/docker/page.mdx
- apps/docs/src/app/developer_guides/frontend/getting_started/page.mdx
> Update getting started for frontend and backend accordingly with the changes

- .github/workflows/ci.yml
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/repository/TeamRepository.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/TeamService.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/collab/service/MailServiceIT.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/service/TeamServiceIT.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/usermanagement/service/UserServiceIT.java
- apps/backend/tools/liquibase/src/main/resources/config/liquibase/tenant/data/fw_app_settings.csv
- pnpm-lock.yaml
* Fix the integration tests failed at backend due to the recent changes
* Add the integration tests in the github actions
* Disable the mail test due to the recent changes of email implementation and we will re-add them in the future
> Fix the integration tests failed due to the recent changes at backend

- README.md
- apps/frontend/messages/en.json
- apps/frontend/messages/fr.json
- apps/frontend/src/components/projects/project-edit-dialog.tsx
- apps/frontend/src/components/projects/project-list-view.tsx
- apps/frontend/src/components/projects/project-view.tsx
- apps/frontend/src/components/projects/state-column.tsx
- apps/frontend/src/components/projects/task-detail-sheet.tsx
- apps/frontend/src/components/projects/task-editor-sheet.tsx
- apps/frontend/src/components/ui/file-uploader.tsx
- apps/frontend/src/hooks/use-translations.ts
- apps/frontend/src/lib/actions/project-epic.action.ts
- apps/frontend/src/lib/actions/project-iteration.action.ts
- apps/frontend/src/types/projects.ts
> Project views localization

- README.md
- apps/frontend/messages/en.json
- apps/frontend/messages/fr.json
- apps/frontend/src/components/projects/epic-form-field.tsx
- apps/frontend/src/components/projects/iteration-form-field.tsx
- apps/frontend/src/components/projects/project-epic-dialog.tsx
- apps/frontend/src/components/projects/project-iteration-dialog.tsx
- apps/frontend/src/components/projects/project-view.tsx
- apps/frontend/src/components/projects/task-detail-sheet.tsx
- apps/frontend/src/components/projects/task-editor-sheet.tsx
- apps/frontend/src/components/ui/ext-form.tsx
- apps/frontend/src/hooks/use-translations.ts
> Edit epic and iteration for project task

- apps/frontend/src/components/projects/project-epic-dialog.tsx
- apps/frontend/src/components/projects/task-detail-sheet.tsx
- apps/frontend/src/components/ui/ext-form.tsx
> Form date field improvement

- apps/ops/flowinquiry-docker/Caddyfile_http
- apps/ops/flowinquiry-docker/scripts/install-flowinquiry.sh
- apps/ops/flowinquiry-docker/services_http.yml
> Update install FlowInquiry scripts

- README.md
- apps/ops/flowinquiry-docker/services_http.yml
> Fix bash script command and docker expose port issues

- apps/frontend/messages/en.json
- apps/frontend/messages/fr.json
- apps/frontend/src/components/forms/profile-form.tsx
- apps/frontend/src/components/projects/project-list-view.tsx
- apps/frontend/src/components/projects/project-view.tsx
- apps/frontend/src/components/projects/task-editor-sheet.tsx
- apps/frontend/src/components/teams/team-dashboard.tsx
- apps/frontend/src/components/teams/team-form.tsx
- apps/frontend/src/components/teams/team-list.tsx
- apps/frontend/src/components/teams/team-users.tsx
- apps/frontend/src/components/teams/team-workflow-detail-view.tsx
- apps/frontend/src/components/teams/team-workflow-new.tsx
- apps/frontend/src/components/teams/team-workflows.tsx
- apps/frontend/src/components/teams/ticket-list-view.tsx
- pnpm-lock.yaml
* Fix the layout issues for project view and task editor
* Add tooltip for team descriptions icon
> Minor UI bug fixes

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/TeamRequestService.java
- apps/frontend/src/components/projects/project-view.tsx
- apps/frontend/src/components/projects/task-editor-sheet.tsx
- gradle.properties
> Bug fix for saving project task without sla, refresh kanban board after creating tasks

- apps/frontend/messages/en.json
- apps/frontend/messages/fr.json
- apps/frontend/src/components/shared/user-select.tsx
- apps/frontend/src/components/teams/team-workflow-detail-view.tsx
- apps/frontend/src/components/teams/team-workflow-new-refer-shared-workflow.tsx
- apps/frontend/src/components/teams/team-workflow-new.tsx
> Add missing localization words

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/controller/TeamRequestController.java
- apps/frontend/src/components/users/user-view.tsx
- pnpm-lock.yaml
> Fix the wrong tickets count by day range

- apps/frontend/src/auth.ts
- apps/frontend/src/components/forms/profile-form.tsx
- apps/frontend/src/components/projects/task-detail-sheet.tsx
> Refresh the avatar after the user uploads a new one

- apps/frontend/src/components/admin-panel/collapse-menu-button.tsx
- apps/frontend/src/components/admin-panel/menu.tsx
- apps/frontend/src/components/auth/login-form.tsx
> Fix sidebar menu issues

- apps/ops/flowinquiry-docker/scripts/backend-env.sh
> Use openssl to generate a random string that is compatible with all tested environments.

- README.md
> Fix style issue

- apps/backend/commons/build.gradle
- apps/backend/commons/src/main/java/io/flowinquiry/config/SecurityConfiguration.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/usermanagement/service/OAuth2UserService.java
- apps/backend/server/src/main/resources/config/application.yml
* Add the implmenentation to support oauth2 for google provider
> Support the oath2 login for google provider

- README.md
- apps/docs/src/app/how_to_contributes/localization/page.mdx
- apps/docs/src/app/how_to_contributes/your_first_pr/page.mdx
Update the links base on the recent changes of FlowInquiry
> Update doc links

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/domain/Ticket.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/dto/TicketDTO.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/TicketMapper.java
- apps/backend/tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/002_00_rename_team_request_to_ticket_table.xml
- apps/frontend/src/types/tickets.ts
> Add ticket parent id to ticket table, update entities, mapper and etc

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectSettingController.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/domain/EstimationUnit.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/domain/Project.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/domain/ProjectSetting.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/domain/Ticket.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectSettingRepository.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectSettingService.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectDTO.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectSettingDTO.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/dto/TicketDTO.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/ProjectSettingMapper.java
- apps/backend/commons/src/main/java/io/flowinquiry/utils/JsonbConverter.java
- apps/backend/tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/002_00_rename_team_request_to_ticket_table.xml
> Add project backend stuffs

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/domain/ProjectSetting.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectSettingDTO.java
- apps/frontend/messages/en.json
- apps/frontend/messages/fr.json
- apps/frontend/src/components/projects/project-edit-dialog.tsx
- apps/frontend/src/types/projects.ts
- apps/frontend/src/types/tickets.ts
> Add frontend new entities

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectController.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectRepository.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectService.java
- apps/frontend/src/app/portal/teams/[teamId]/projects/[projectId]/page.tsx
- apps/frontend/src/components/mail/mail-settings.tsx
- apps/frontend/src/components/projects/project-list-view.tsx
- apps/frontend/src/components/projects/project-view.tsx
- apps/frontend/src/components/projects/task-detail-sheet.tsx
- apps/frontend/src/lib/actions/project.action.ts
> Set project navigation base on project short name

- README.md
- apps/docs/src/app/user_guides/setup/basic_installation/page.mdx
- apps/ops/flowinquiry-docker/scripts/install-flowinquiry.sh
- apps/ops/flowinquiry-docker/scripts/run-docker-compose.sh
- apps/ops/flowinquiry-docker/scripts/shared.sh
> Ppdate document to instruct user install flowinquiry manually steps by steps with scripts

- apps/backend/server/src/main/resources/banner.txt
- apps/backend/server/src/main/resources/config/application.yml
- apps/frontend/src/components/teams/team-tickets-unassigned.tsx
- apps/frontend/src/components/teams/tickets-overdue.tsx
- apps/ops/flowinquiry-docker/scripts/install-flowinquiry.sh
> Update flowinquiry version, and fix the ticket link issue

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/repository/TicketRepository.java
- apps/docs/package.json
- apps/frontend/package.json
- apps/frontend/src/components/shared/truncate-html-label.tsx
- apps/frontend/src/components/teams/team-new-ticket-dialog.tsx
- apps/frontend/src/components/teams/team-tickets-unassigned.tsx
- apps/frontend/src/components/teams/tickets-overdue.tsx
- apps/frontend/src/lib/actions/tickets.action.ts
- apps/frontend/src/types/tickets.ts
- package.json
- pnpm-lock.yaml
> UI improvements and minor bug fixes

- apps/frontend/global-setup.ts
- apps/frontend/playwright.config.ts
- apps/frontend/src/components/authorities/authority-form.tsx
- apps/frontend/src/components/authorities/authority-list.tsx
- apps/frontend/src/components/authorities/authority-view.tsx
- apps/frontend/src/components/projects/project-edit-dialog.tsx
- apps/frontend/src/components/projects/project-view.tsx
- apps/frontend/src/components/workflows/workflow-editor-form.tsx
- apps/frontend/src/components/workflows/workflow-states-select-field.tsx
- apps/frontend/tests/authorities.spec.ts
- apps/frontend/tests/helpers/project-fixtures.ts
- apps/frontend/tests/helpers/team-fixtures.ts
- apps/frontend/tests/pages/projects-page.ts
- apps/frontend/tests/projects.spec.ts
- apps/frontend/tests/teams.spec.ts
- apps/frontend/tests/users.spec.ts
> Add more playwright tests for project

- apps/backend/commons/src/main/java/io/flowinquiry/modules/usermanagement/controller/PublicUserController.java
- apps/backend/commons/src/main/java/io/flowinquiry/query/Filter.java
- apps/backend/commons/src/main/java/io/flowinquiry/query/FilterOperator.java
- apps/backend/commons/src/main/java/io/flowinquiry/query/GroupFilter.java
- apps/backend/commons/src/main/java/io/flowinquiry/query/QueryUtils.java
- apps/backend/server/build.gradle
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/service/ProjectServiceIT.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/service/TeamServiceIT.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/service/TicketServiceIT.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/service/WorkflowServiceIT.java
> Add more integration tests, collect the jacoco report files

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/controller/ProjectController.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectRepository.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/ProjectService.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/service/ProjectServiceIT.java
- apps/backend/tools/liquibase/src/main/resources/config/liquibase/tenant/changelog/test-data-changelog.xml
- apps/backend/tools/liquibase/src/main/resources/config/liquibase/tenant/data/test/fw_project_test.csv
- apps/frontend/src/app/portal/projects/page.tsx
- apps/frontend/src/app/portal/teams/[teamId]/projects/page.tsx
- apps/frontend/src/components/projects/team-project-list-view.tsx
- apps/frontend/src/lib/menu-list.ts
> Add project link to the main navigator, update project IT tests

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/repository/ProjectRepository.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/dto/ProjectDTO.java
- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/service/mapper/ProjectMapper.java
- apps/frontend/messages/en.json
- apps/frontend/messages/fr.json
- apps/frontend/src/app/portal/projects/page.tsx
- apps/frontend/src/components/projects/project-list-view.tsx
- apps/frontend/src/components/projects/team-project-list-view.tsx
- apps/frontend/src/components/ui/link.tsx
- apps/frontend/src/components/ui/toggle-group.tsx
- apps/frontend/src/components/ui/toggle.tsx
- apps/frontend/src/lib/actions/project.action.ts
- apps/frontend/src/types/projects.ts
> Add list user project page

- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/controller/ProjectEpicControllerIT.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/controller/ProjectIterationControllerIT.java
> Add more backend integration tests for epic and iteration services

- apps/ops/flowinquiry-docker/services_http.yml
- apps/ops/flowinquiry-docker/services_https.yml
- gradle.properties
- version.json
> Prepare for release

- apps/backend/commons/src/main/java/io/flowinquiry/config/AsyncConfiguration.java
- apps/backend/commons/src/main/java/io/flowinquiry/security/SecurityUtils.java
- apps/backend/commons/src/main/java/io/flowinquiry/tenant/TenantAwareDelegatingTaskExecutor.java
- apps/backend/commons/src/main/java/io/flowinquiry/tenant/TenantContext.java
- apps/backend/commons/src/main/java/io/flowinquiry/tenant/domain/TenantScopedAuditingEntity.java
- apps/backend/commons/src/main/java/io/flowinquiry/tenant/domain/TenantScopedCreationAuditingEntity.java
- apps/backend/commons/src/main/java/io/flowinquiry/tenant/domain/TenantScopedEntity.java
- apps/backend/commons/src/main/java/io/flowinquiry/tenant/filter/TenantContextFilter.java
- apps/backend/server/src/test/java/io/flowinquiry/it/WithTestTenant.java
- apps/backend/server/src/test/java/io/flowinquiry/it/WithTestTenantExtension.java
> Pass tenant info to the async tasks

- apps/backend/commons/src/main/java/io/flowinquiry/modules/teams/utils/ProjectIterationNameGenerator.java
- apps/backend/server/src/test/java/io/flowinquiry/modules/teams/utils/ProjectIterationNameGeneratorTest.java
A service that automatically generates the iteration name from the previous iteration
> Add sprint itreation name generator service

- .github/workflows/ci.yml
- .github/workflows/coverage-comment.yml
> Fix CI pipeline failure on forked PRs
